### ISSUE TITLE
DBの設定（Roomデータベース本体の記述）

### ISSUE THREAD

**Issue by ToboMasaya** [kiesproject/WhiteboardFormatter#5]

**Comment by pikohan-suzuki** [comment]
## 概要
Roomデータベースを定義するファイルを作成する。
## 目的
作成したEntityやDaoをDBに登録し、アプリ内でRoomデータベースを使用できる状態にすること。
##先行作業
DBのEntity
https://github.com/kiesproject/WhiteboardFormatter/issues/9
DBのDao
https://github.com/kiesproject/WhiteboardFormatter/issues/8
## タスク
1. ファイルを所定の位置に作成し、その中にAppDatabaseのクラスを作成
2. 作成したEntitiyとDaoを設定します。

## 実装方法
1. app/data/AppDatabase.ktの位置にファイルを作成します。
2. 作成したファイル内にRoomDatabase()を継承した抽象クラスAppDatabaseを@Databaseアノテーションをつけて作成します。
3. entityは@Databaseアノテーションの中に記述します。versionは=1でお願いします。
4 そのクラスの中に抽象クラスとして、作成したDaoインターフェースを使用して、daoを定義します。
5. ヤバ見るにはMigrationなどが記述されていますがそれは無視でいいです。同様に、 RoomDataCallbackもいらないです。また、それを適応するaddMigrationやaddCallbackも実装しなくていいです。

**classの実装例**

| class名  | 継承 | 引数  | 備考 |
|---|---|---|---|
| AppDatabase  | RoomDatabase  | なし| @Databaseアノテーションをつける |

## 備考
おそらくネット上の実装例みても、何書いてあるのかよくわからないし僕も理解してないから、ヤバみるを参考にして作ってください。わからないことは ****何でも**** 聞いてください。
*version =1 で、MIGRATIONとCallbackはいらないです（再掲）*
